/**
 * End-to-end smoke test. Drives the real HTTP surface — register, upload,
 * place fields, send, sign, seal, verify — against a throwaway database, and
 * checks the seal actually detects tampering.
 *
 *   npm run smoke
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'signflow-smoke-'));
const PORT = 3999;
const BASE = `http://127.0.0.1:${PORT}`;

let passed = 0;
let failed = 0;
const cookies = new Map();

function check(label, condition, extra = '') {
  if (condition) { passed++; console.log(`  ok    ${label}`); }
  else { failed++; console.log(`  FAIL  ${label}${extra ? `\n          ${extra}` : ''}`); }
}

/* -------------------------------------------------- tiny cookie-aware fetch */

function jar() {
  return [...cookies.entries()].map(([k, v]) => `${k}=${v}`).join('; ');
}

async function req(method, url, { body, headers = {}, redirect = 'manual' } = {}) {
  const res = await fetch(BASE + url, {
    method,
    redirect,
    headers: { ...(cookies.size ? { cookie: jar() } : {}), ...headers },
    body,
  });
  for (const raw of res.headers.getSetCookie?.() || []) {
    const [pair] = raw.split(';');
    const idx = pair.indexOf('=');
    cookies.set(pair.slice(0, idx), pair.slice(idx + 1));
  }
  return res;
}

const form = (obj) => {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(obj)) {
    for (const item of [].concat(v)) p.append(k, String(item));
  }
  return { body: p, headers: { 'content-type': 'application/x-www-form-urlencoded' } };
};

/* ------------------------------------------------------------ test fixture */

async function makeTestPdf() {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  for (let i = 0; i < 2; i++) {
    const page = pdf.addPage([595.28, 841.89]);
    page.drawText(i === 0 ? 'ICT Acceptable Usage Policy' : 'Acceptance', {
      x: 56, y: 760, size: 20, font: bold, color: rgb(0.1, 0.2, 0.42),
    });
    page.drawText('This is a test document generated by the smoke test.', {
      x: 56, y: 720, size: 11, font,
    });
    if (i === 1) {
      page.drawText('Signature:', { x: 56, y: 300, size: 11, font });
      page.drawText('Date:', { x: 56, y: 240, size: 11, font });
    }
  }
  return Buffer.from(await pdf.save());
}

/** Reads back the text of one page of a produced PDF, for layout assertions. */
async function pageText(bytes, pageNumber) {
  const { getDocument } = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const pdf = await getDocument({ data: new Uint8Array(bytes), useSystemFonts: true }).promise;
  const content = await (await pdf.getPage(pageNumber)).getTextContent();
  return content.items.map((i) => i.str).join(' ');
}

/** A 1x1 transparent PNG, enough to prove the image path works. */
const PNG_1PX =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

/* --------------------------------------------------------------- the run */

async function run() {
  console.log('\nSignFlow smoke test\n');

  // --- 1. register ---------------------------------------------------------
  const email = `owner-${Date.now()}@example.test`;
  let res = await req('POST', '/register', form({
    email, display_name: 'Test Owner', org_name: 'Test Org', password: 'a-long-enough-password',
  }));
  // The first account on an empty installation is the administrator, and lands
  // on the team page rather than the document list.
  check('the founding account is created', res.status === 302 && res.headers.get('location') === '/team',
    `got ${res.status} → ${res.headers.get('location')}`);

  res = await req('GET', '/documents');
  check('dashboard loads when signed in', res.status === 200);

  // The brand assets are derived by scripts/build-brand.js; a fresh clone that
  // skipped that step should fail loudly here rather than ship broken images.
  for (const asset of ['logo-web.png', 'logo-print.png', 'logo-mark.png']) {
    const r = await req('GET', `/static/brand/${asset}`);
    check(`brand asset ${asset} is served`, r.status === 200 && Number(r.headers.get('content-length')) > 1000,
      `status ${r.status}, ${r.headers.get('content-length')} bytes`);
  }

  // --- 2. upload -----------------------------------------------------------
  const pdfBytes = await makeTestPdf();
  const originalSha = crypto.createHash('sha256').update(pdfBytes).digest('hex');

  const fd = new FormData();
  fd.append('pdf', new Blob([pdfBytes], { type: 'application/pdf' }), 'policy.pdf');
  fd.append('title', 'ICT Policy');
  fd.append('message', 'Please read and sign.');
  fd.append('expires_in_days', '30');
  fd.append('recipient_name', 'Test Signer');
  fd.append('recipient_email', 'signer@example.test');

  res = await req('POST', '/documents/new', { body: fd });
  const location = res.headers.get('location') || '';
  const docId = location.match(/\/documents\/([0-9a-f-]{36})\/prepare/)?.[1];
  check('upload redirects to the field placer', !!docId, `got ${res.status} → ${location}`);
  if (!docId) throw new Error('cannot continue without a document');

  res = await req('GET', `/documents/${docId}/prepare`);
  const prepareHtml = await res.text();
  check('placer page renders', res.status === 200 && prepareHtml.includes('Placing fields for'));

  const recipientId = prepareHtml.match(/data-id="([0-9a-f-]{36})"/)?.[1];
  check('recipient is on the placer page', !!recipientId);

  // --- 3. place fields -----------------------------------------------------
  const fieldIds = {
    signature: crypto.randomUUID(),
    date: crypto.randomUUID(),
    name: crypto.randomUUID(),
    company: crypto.randomUUID(),
    accept: crypto.randomUUID(),
    stamp: crypto.randomUUID(),
    qr: crypto.randomUUID(),
  };

  res = await req('PUT', `/api/documents/${docId}/fields`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      fields: [
        { id: fieldIds.signature, type: 'signature', recipient_id: recipientId, page: 1, x: 0.18, y: 0.60, w: 0.32, h: 0.09 },
        { id: fieldIds.date, type: 'date_signed', recipient_id: recipientId, page: 1, x: 0.18, y: 0.70, w: 0.18, h: 0.03 },
        { id: fieldIds.name, type: 'name', recipient_id: recipientId, page: 1, x: 0.50, y: 0.63, w: 0.24, h: 0.03 },
        { id: fieldIds.company, type: 'company', recipient_id: recipientId, page: 1, x: 0.50, y: 0.70, w: 0.24, h: 0.03 },
        { id: fieldIds.accept, type: 'checkbox', recipient_id: recipientId, page: 0, x: 0.10, y: 0.50, w: 0.025, h: 0.018 },
        { id: fieldIds.stamp, type: 'stamp', recipient_id: null, page: 0, x: 0.62, y: 0.10, w: 0.22, h: 0.06, meta: { text: 'APPROVED', dated: true } },
        { id: fieldIds.qr, type: 'qrcode', recipient_id: null, page: 1, x: 0.80, y: 0.85, w: 0.10, h: 0.07, meta: { data: '' } },
        // Should be dropped: the page does not exist.
        { id: crypto.randomUUID(), type: 'textbox', recipient_id: recipientId, page: 9, x: 0.1, y: 0.1, w: 0.2, h: 0.03 },
        // Should be dropped: not a real type.
        { id: crypto.randomUUID(), type: 'nonsense', recipient_id: recipientId, page: 0, x: 0.1, y: 0.1, w: 0.2, h: 0.03 },
      ],
    }),
  });
  const saveResult = await res.json();
  check('fields save, invalid ones rejected', res.status === 200 && saveResult.saved === 7,
    `saved ${saveResult.saved}, expected 7`);

  // --- 4. send -------------------------------------------------------------
  res = await req('POST', `/documents/${docId}/send`);
  check('send redirects to the document', res.status === 302);

  res = await req('GET', `/documents/${docId}`);
  const docHtml = await res.text();
  const token = docHtml.match(/\/sign\/([A-Za-z0-9_-]{40,})/)?.[1];
  check('a signing token was issued', !!token);
  check('original hash shown on the document page', docHtml.includes(originalSha));

  // --- 5. sign -------------------------------------------------------------
  // The signer is a different browser: drop the owner's session.
  const ownerCookies = new Map(cookies);
  cookies.clear();

  res = await req('GET', `/sign/${token}`);
  const signHtml = await res.text();
  check('signing page opens without an account', res.status === 200 && signHtml.includes('Review &amp; sign'));
  check('POPIA notice is shown before signing', signHtml.includes('IP address') && signHtml.includes('POPIA'));

  // Consent withheld must be refused.
  res = await req('POST', `/sign/${token}`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ values: {} }),
  });
  check('signing without consent is refused', res.status === 400);

  // Missing a required field must be refused.
  res = await req('POST', `/sign/${token}`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ consent: true, values: {} }),
  });
  const missing = await res.json();
  check('missing required fields are refused', res.status === 400 && /Still to complete/.test(missing.error || ''),
    JSON.stringify(missing));

  // The real signature.
  res = await req('POST', `/sign/${token}`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      consent: true,
      values: {
        [fieldIds.signature]: PNG_1PX,
        [fieldIds.company]: 'Protea Test (Pty) Ltd',
        [fieldIds.accept]: true,
        // Deliberately try to forge the auto fields — the server must ignore these.
        [fieldIds.date]: '1999-01-01',
        [fieldIds.name]: 'Someone Else',
      },
    }),
  });
  const signed = await res.json();
  check('signature accepted', res.status === 200 && signed.ok === true, JSON.stringify(signed));

  res = await req('GET', `/sign/${token}/done`);
  const doneHtml = await res.text();
  check('done page confirms completion', res.status === 200 && doneHtml.includes('Signed'));

  // Re-using a spent link must not open the document again.
  res = await req('GET', `/sign/${token}`);
  const replayHtml = await res.text();
  check('a spent signing link cannot be reused', replayHtml.includes('already signed'));

  // --- 6. the seal ---------------------------------------------------------
  res = await req('GET', `/sign/${token}/signed.pdf`);
  const sealedBytes = Buffer.from(await res.arrayBuffer());
  check('sealed PDF downloads', res.status === 200 && sealedBytes.length > 1000);

  const sealedSha = crypto.createHash('sha256').update(sealedBytes).digest('hex');
  const sealedPdf = await PDFDocument.load(sealedBytes);
  check('certificate page was appended', sealedPdf.getPageCount() === 3,
    `page count ${sealedPdf.getPageCount()}, expected 3`);

  // The signature has to certify itself on the page, not just in the audit
  // trail — a printed copy travels without either.
  const signaturePageText = await pageText(sealedBytes, 2);
  check('signature is certified on the page, not just stamped',
    signaturePageText.includes('Signed by') && signaturePageText.includes('Test Signer'),
    signaturePageText.slice(0, 200));
  check('certification block carries the document reference',
    signaturePageText.includes(`Doc ${docId.slice(0, 13)}`), signaturePageText.slice(0, 200));
  check('certification block carries the signing time',
    /\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}\(UTC[+-]\d{2}:\d{2}\)/.test(signaturePageText),
    signaturePageText.slice(0, 200));

  // Every page of the document itself carries a provenance line, so a page
  // separated from the bundle still says which record it belongs to. The
  // certificate has its own footer and must not be stamped twice.
  const footerNeedle = `Signed via SignFlow`;
  const pageTexts = await Promise.all([1, 2, 3].map((n) => pageText(sealedBytes, n)));
  check('every document page carries the provenance footer',
    pageTexts[0].includes(footerNeedle) && pageTexts[0].includes(docId) &&
    pageTexts[1].includes(footerNeedle) && pageTexts[1].includes(docId),
    `p1 ${pageTexts[0].includes(footerNeedle)}, p2 ${pageTexts[1].includes(footerNeedle)}`);
  check('the certificate is not double-stamped',
    !pageTexts[2].includes(footerNeedle) && pageTexts[2].includes('Certificate page'),
    pageTexts[2].slice(-160));

  // --- 7. verification -----------------------------------------------------
  // This exact URL is printed inside every sealed certificate and encoded into
  // QR-code fields. Those documents cannot be reissued, so it has to keep
  // resolving for as long as any of them exist — moving it is not an option.
  res = await req('GET', `/verify/${docId}`);
  const verifyHtml = await res.text();
  check('the URL printed inside sealed PDFs still resolves',
    res.status === 200 && verifyHtml.includes(sealedSha), `got ${res.status}`);

  res = await req('GET', '/');
  check('the root serves the verification page without an account', res.status === 200);

  res = await req('GET', '/verify');
  check('the old /verify redirects to the root',
    res.status === 301 && res.headers.get('location') === '/',
    `${res.status} → ${res.headers.get('location')}`);
  check('verification shows the audit trail', verifyHtml.includes('Signature applied'));
  check('auto fields were not forged', !verifyHtml.includes('Someone Else'));

  const upload = (bytes, name) => {
    const f = new FormData();
    f.append('pdf', new Blob([bytes], { type: 'application/pdf' }), name);
    return req('POST', '/check', { body: f, redirect: 'follow' });
  };

  res = await upload(sealedBytes, 'signed.pdf');
  const goodHtml = await res.text();
  check('an untouched sealed PDF verifies', goodHtml.includes('intact and unaltered'));

  // Tamper: flip a byte well inside the file.
  const tampered = Buffer.from(sealedBytes);
  tampered[Math.floor(tampered.length / 2)] ^= 0xff;
  res = await upload(tampered, 'tampered.pdf');
  const badHtml = await res.text();
  check('a tampered PDF fails verification', badHtml.includes('No match'));

  res = await upload(pdfBytes, 'original.pdf');
  const origHtml = await res.text();
  check('the original upload is recognised as the original', origHtml.includes('Matches the original upload'));

  // --- 8. access control ---------------------------------------------------
  cookies.clear();
  res = await req('GET', `/documents/${docId}`);
  check('signed-out users cannot open a document', res.status === 302 && res.headers.get('location') === '/login');

  // A second account must not be able to reach the first one's document.
  // Registration is invitation-only, so the owner has to issue one first.
  cookies.clear();
  for (const [k, v] of ownerCookies) cookies.set(k, v);

  const colleagueEmail = `colleague-${Date.now()}@example.test`;
  await req('POST', '/team/invite', form({ email: colleagueEmail, role: 'member' }));
  const teamHtml = await (await req('GET', '/team')).text();
  const inviteToken = teamHtml.match(/\/invite\/([A-Za-z0-9_-]{40,})/)?.[1];
  check('the owner can invite a colleague', !!inviteToken);

  cookies.clear();
  res = await req('POST', `/invite/${inviteToken}`, form({
    display_name: 'A Colleague', password: 'another-long-password', password_confirm: 'another-long-password',
  }));
  check('the colleague accepts the invitation',
    res.status === 302 && res.headers.get('location') === '/documents',
    `got ${res.status} → ${res.headers.get('location')}`);

  res = await req('GET', `/documents/${docId}`);
  check('another account gets 404, not the document', res.status === 404);

  res = await req('PUT', `/api/documents/${docId}/fields`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ fields: [] }),
  });
  check('another account cannot rewrite the fields', res.status === 404);

  // A member is not an administrator just because they were invited by one.
  res = await req('GET', '/team');
  check('a colleague cannot reach the team page', res.status === 404, `got ${res.status}`);

  // The owner must not be able to edit fields after sending either.
  cookies.clear();
  for (const [k, v] of ownerCookies) cookies.set(k, v);
  res = await req('PUT', `/api/documents/${docId}/fields`, {
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ fields: [] }),
  });
  check('a sent document is locked against field edits', res.status === 409);

  console.log(`\n${passed} passed, ${failed} failed\n`);
  return failed === 0;
}

/* ------------------------------------------------------------------ driver */

const server = spawn(process.execPath, ['src/server.js'], {
  cwd: path.resolve(import.meta.dirname, '..'),
  env: {
    ...process.env,
    NODE_ENV: 'development',
    PORT: String(PORT),
    BASE_URL: BASE,
    STORAGE_DIR: TMP,
    DB_PATH: path.join(TMP, 'smoke.db'),
    SESSION_SECRET: crypto.randomBytes(32).toString('hex'),
    APP_KEY: crypto.randomBytes(32).toString('hex'),
    BRAND_NAME: 'SignFlow',
  },
  stdio: ['ignore', 'pipe', 'pipe'],
});

let serverLog = '';
server.stdout.on('data', (d) => { serverLog += d; });
server.stderr.on('data', (d) => { serverLog += d; });

async function waitForServer(timeoutMs = 15000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await fetch(`${BASE}/login`);
      return true;
    } catch {
      await new Promise((r) => setTimeout(r, 150));
    }
  }
  return false;
}

let ok = false;
try {
  if (!(await waitForServer())) throw new Error(`server never came up:\n${serverLog}`);
  ok = await run();
} catch (err) {
  console.error('\nSmoke test crashed:', err.message);
  if (serverLog) console.error('\n--- server output ---\n' + serverLog);
} finally {
  server.kill();
  // Windows keeps the SQLite WAL files locked until the child has actually
  // gone, so wait for the exit before trying to remove the scratch directory.
  await new Promise((r) => (server.exitCode === null ? server.once('exit', r) : r()));
  try {
    fs.rmSync(TMP, { recursive: true, force: true, maxRetries: 10, retryDelay: 120 });
  } catch (err) {
    console.warn(`(could not remove ${TMP}: ${err.code})`);
  }
}

if (!ok && serverLog.includes('Error')) console.error('\n--- server output ---\n' + serverLog);
process.exit(ok ? 0 : 1);
